const FETCH_STATES = {
  FETCH_STARTED   : "@@FETCH_STARTED@@",
  FETCH_COMPLETED : "@@FETCH_COMPLETED@@",
  FETCH_ERROR     : "@@FETCH_ERROR@@",
  FETCH_CANCELLED : "@@FETCH_CANCELLED@@"
};

module.exports = FETCH_STATES;
